name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: true
      - name: Pull submodule
        run: |
          git pull --recurse-submodules
          git submodule update --init --recursive --remote
      - name: Push changes
        run: |
          git config --global user.name 'smallstepman'
          git config --global user.email 'smallstepman@users.noreply.github.com'
          git add .
          git commit -m "Automated report"
          git push
