name: CI
# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
on: [repository_dispatch]
 
#   workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Event Information
        run: |
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'"
#       - name: PONG - Dispatch response to received PING
#         if: github.event.action == 'ping'
#         run: |
#           curl -X POST https://api.github.com/repos/marcnuri-demo/actions-remote-dispatch-a/dispatches \
#           -H 'Accept: application/vnd.github.everest-preview+json' \
#           -u ${{ secrets.ACCESS_TOKEN }} \
#           --data '{"event_type": "pong", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: true
      - name: Pull submodule
        run: |
          git pull --recurse-submodules
          git submodule update --init --recursive --remote
      - name: Push changes
        run: |
          git config --global user.name 'smallstepman'
          git config --global user.email 'smallstepman@users.noreply.github.com'
          git add .
          git commit -m "Automated report"
          git push

